name: GHPages => Push main

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      # Ajouter ici des tests si nécessaire

      - name: Build code
        working-directory: ./frontend
        run: npm run build

      - name: Generate artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: build
          path: ./frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Config GHPages
        uses: actions/configure-pages@v4

      - name: Deploy to GHPages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: build
          token: ${{secrets.GITHUB_TOKEN}}
